
import java.awt.Color;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Bryce
 */
public class Database extends javax.swing.JFrame {

    /**
     * Creates new form Database
     */
    boolean inventory = true;
    boolean orders = false;
    boolean services = false;
    boolean suppliers = false;

    public Database() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        invPanelBtn = new javax.swing.JButton();
        ordersSummBtn = new javax.swing.JButton();
        servicesSummBtn = new javax.swing.JButton();
        suppliersSummBtn1 = new javax.swing.JButton();
        mainPanel = new javax.swing.JPanel();
        inventPanel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        itemNameTF = new javax.swing.JTextField();
        quantityTF = new javax.swing.JTextField();
        supplierTF = new javax.swing.JTextField();
        statusCB = new javax.swing.JComboBox<>();
        createBtn = new javax.swing.JButton();
        editBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        backBtn1 = new javax.swing.JButton();
        ExitBtn1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        ordersPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        allOrdersTable = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        itemNameTF3 = new javax.swing.JTextField();
        quantityTF3 = new javax.swing.JTextField();
        supplierTF2 = new javax.swing.JTextField();
        statusCB2 = new javax.swing.JComboBox<>();
        createBtn3 = new javax.swing.JButton();
        editBtn3 = new javax.swing.JButton();
        deleteBtn3 = new javax.swing.JButton();
        backBtn5 = new javax.swing.JButton();
        ExitBtn4 = new javax.swing.JButton();
        servicesPanel = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel16 = new javax.swing.JPanel();
        itemNameTF4 = new javax.swing.JTextField();
        quantityTF4 = new javax.swing.JTextField();
        supplierTF3 = new javax.swing.JTextField();
        statusCB3 = new javax.swing.JComboBox<>();
        createBtn4 = new javax.swing.JButton();
        editBtn4 = new javax.swing.JButton();
        deleteBtn4 = new javax.swing.JButton();
        backBtn6 = new javax.swing.JButton();
        ExitBtn5 = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        suppliersPanel = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        itemNameTF1 = new javax.swing.JTextField();
        quantityTF1 = new javax.swing.JTextField();
        createBtn1 = new javax.swing.JButton();
        editBtn1 = new javax.swing.JButton();
        deleteBtn1 = new javax.swing.JButton();
        backBtn3 = new javax.swing.JButton();
        ExitBtn2 = new javax.swing.JButton();
        jPanel15 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 450));
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel8.setPreferredSize(new java.awt.Dimension(350, 350));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel8, java.awt.BorderLayout.EAST);

        jPanel9.setPreferredSize(new java.awt.Dimension(450, 450));
        jPanel9.setLayout(new java.awt.GridLayout(1, 3));

        invPanelBtn.setText("Inventory");
        invPanelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                invPanelBtnActionPerformed(evt);
            }
        });
        jPanel9.add(invPanelBtn);

        ordersSummBtn.setText("Orders");
        ordersSummBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ordersSummBtnActionPerformed(evt);
            }
        });
        jPanel9.add(ordersSummBtn);

        servicesSummBtn.setText("Services");
        servicesSummBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                servicesSummBtnActionPerformed(evt);
            }
        });
        jPanel9.add(servicesSummBtn);

        suppliersSummBtn1.setText("Suppliers");
        suppliersSummBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suppliersSummBtn1ActionPerformed(evt);
            }
        });
        jPanel9.add(suppliersSummBtn1);

        jPanel2.add(jPanel9, java.awt.BorderLayout.WEST);

        getContentPane().add(jPanel2, java.awt.BorderLayout.NORTH);

        mainPanel.setLayout(new java.awt.CardLayout());

        inventPanel.setPreferredSize(new java.awt.Dimension(600, 450));
        inventPanel.setLayout(new java.awt.BorderLayout());

        jPanel3.setPreferredSize(new java.awt.Dimension(250, 250));

        itemNameTF.setForeground(new java.awt.Color(204, 204, 204));
        itemNameTF.setText("Item Name");
        itemNameTF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                itemNameTFFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                itemNameTFFocusLost(evt);
            }
        });

        quantityTF.setForeground(new java.awt.Color(204, 204, 204));
        quantityTF.setText("Quantity");
        quantityTF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                quantityTFFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                quantityTFFocusLost(evt);
            }
        });

        supplierTF.setForeground(new java.awt.Color(204, 204, 204));
        supplierTF.setText("Supplier");
        supplierTF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                supplierTFFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                supplierTFFocusLost(evt);
            }
        });

        statusCB.setForeground(new java.awt.Color(204, 204, 204));
        statusCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Available", "Not Available" }));

        createBtn.setText("Create");

        editBtn.setText("Edit");

        deleteBtn.setText("Delete");

        backBtn1.setText("Back");
        backBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtn1ActionPerformed(evt);
            }
        });

        ExitBtn1.setText("Exit");
        ExitBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitBtn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(backBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ExitBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(createBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(editBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(statusCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(supplierTF, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(quantityTF, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(itemNameTF, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(itemNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(quantityTF, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(supplierTF, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(statusCB, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ExitBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        inventPanel.add(jPanel3, java.awt.BorderLayout.EAST);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item", "Quantity", "Supplier", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
        }

        jPanel4.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        inventPanel.add(jPanel4, java.awt.BorderLayout.CENTER);

        mainPanel.add(inventPanel, "card4");

        ordersPanel.setLayout(new java.awt.BorderLayout());

        jPanel1.setPreferredSize(new java.awt.Dimension(200, 200));
        jPanel1.setLayout(new java.awt.BorderLayout());

        allOrdersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Client", "Orders", "Time Slot", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(allOrdersTable);

        jPanel1.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jPanel7.setPreferredSize(new java.awt.Dimension(250, 250));

        itemNameTF3.setForeground(new java.awt.Color(204, 204, 204));
        itemNameTF3.setText("Item Name");
        itemNameTF3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                itemNameTF3FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                itemNameTF3FocusLost(evt);
            }
        });

        quantityTF3.setForeground(new java.awt.Color(204, 204, 204));
        quantityTF3.setText("Orders");
        quantityTF3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                quantityTF3FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                quantityTF3FocusLost(evt);
            }
        });

        supplierTF2.setForeground(new java.awt.Color(204, 204, 204));
        supplierTF2.setText("Time Slot");
        supplierTF2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                supplierTF2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                supplierTF2FocusLost(evt);
            }
        });

        statusCB2.setForeground(new java.awt.Color(204, 204, 204));
        statusCB2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Available", "Not Available" }));

        createBtn3.setText("Create");

        editBtn3.setText("Edit");

        deleteBtn3.setText("Delete");

        backBtn5.setText("Back");
        backBtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtn5ActionPerformed(evt);
            }
        });

        ExitBtn4.setText("Exit");
        ExitBtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitBtn4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(deleteBtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(backBtn5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ExitBtn4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(createBtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(editBtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(statusCB2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(supplierTF2, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(quantityTF3, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(itemNameTF3, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(itemNameTF3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(quantityTF3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(supplierTF2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(statusCB2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createBtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editBtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deleteBtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backBtn5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ExitBtn4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel1.add(jPanel7, java.awt.BorderLayout.EAST);

        ordersPanel.add(jPanel1, java.awt.BorderLayout.CENTER);

        mainPanel.add(ordersPanel, "card3");

        servicesPanel.setPreferredSize(new java.awt.Dimension(600, 450));
        servicesPanel.setLayout(new java.awt.BorderLayout());

        jPanel10.setLayout(new java.awt.BorderLayout());

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Client", "Service", "Time Slot", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable2);

        jPanel10.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        jPanel16.setPreferredSize(new java.awt.Dimension(250, 250));

        itemNameTF4.setForeground(new java.awt.Color(204, 204, 204));
        itemNameTF4.setText("Client");
        itemNameTF4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                itemNameTF4FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                itemNameTF4FocusLost(evt);
            }
        });

        quantityTF4.setForeground(new java.awt.Color(204, 204, 204));
        quantityTF4.setText("Service");
        quantityTF4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                quantityTF4FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                quantityTF4FocusLost(evt);
            }
        });

        supplierTF3.setForeground(new java.awt.Color(204, 204, 204));
        supplierTF3.setText("Time Slot");
        supplierTF3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                supplierTF3FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                supplierTF3FocusLost(evt);
            }
        });

        statusCB3.setForeground(new java.awt.Color(204, 204, 204));
        statusCB3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Available", "Not Available" }));

        createBtn4.setText("Create");

        editBtn4.setText("Edit");

        deleteBtn4.setText("Delete");

        backBtn6.setText("Back");
        backBtn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtn6ActionPerformed(evt);
            }
        });

        ExitBtn5.setText("Exit");
        ExitBtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitBtn5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(deleteBtn4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81))
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addComponent(backBtn6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ExitBtn5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                        .addComponent(createBtn4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(editBtn4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(statusCB3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(supplierTF3, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(quantityTF4, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(itemNameTF4, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(itemNameTF4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(quantityTF4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(supplierTF3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(statusCB3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createBtn4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editBtn4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deleteBtn4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backBtn6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ExitBtn5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel10.add(jPanel16, java.awt.BorderLayout.EAST);

        servicesPanel.add(jPanel10, java.awt.BorderLayout.CENTER);

        jPanel11.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel11.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel11.add(jPanel12, java.awt.BorderLayout.CENTER);

        servicesPanel.add(jPanel11, java.awt.BorderLayout.SOUTH);

        mainPanel.add(servicesPanel, "card2");

        suppliersPanel.setLayout(new java.awt.BorderLayout());

        jPanel14.setPreferredSize(new java.awt.Dimension(250, 250));

        itemNameTF1.setForeground(new java.awt.Color(204, 204, 204));
        itemNameTF1.setText("Name");
        itemNameTF1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                itemNameTF1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                itemNameTF1FocusLost(evt);
            }
        });

        quantityTF1.setForeground(new java.awt.Color(204, 204, 204));
        quantityTF1.setText("Contact");
        quantityTF1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                quantityTF1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                quantityTF1FocusLost(evt);
            }
        });

        createBtn1.setText("Create");

        editBtn1.setText("Edit");

        deleteBtn1.setText("Delete");

        backBtn3.setText("Back");
        backBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtn3ActionPerformed(evt);
            }
        });

        ExitBtn2.setText("Exit");
        ExitBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitBtn2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deleteBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(66, 66, 66))
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel14Layout.createSequentialGroup()
                                .addComponent(backBtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                                .addComponent(ExitBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                                .addComponent(createBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(editBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(quantityTF1)
                        .addComponent(itemNameTF1, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(itemNameTF1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(quantityTF1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(deleteBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backBtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ExitBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45))
        );

        suppliersPanel.add(jPanel14, java.awt.BorderLayout.EAST);

        jPanel15.setBackground(new java.awt.Color(255, 255, 255));
        jPanel15.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel15.setLayout(new java.awt.BorderLayout());

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Contact"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jTable3);

        jPanel15.add(jScrollPane4, java.awt.BorderLayout.CENTER);

        suppliersPanel.add(jPanel15, java.awt.BorderLayout.CENTER);

        mainPanel.add(suppliersPanel, "card5");

        getContentPane().add(mainPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemNameTFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_itemNameTFFocusGained
        // TODO add your handling code here:
        if(itemNameTF.getText().equals("Item Name"))
        {
            itemNameTF.setText("");
            itemNameTF.setForeground(new Color(153,153,153));
        }        
    }//GEN-LAST:event_itemNameTFFocusGained

    private void itemNameTFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_itemNameTFFocusLost
        // TODO add your handling code here:
        if(itemNameTF.getText().equals(""))
        {
            itemNameTF.setText("Item Name");
            itemNameTF.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_itemNameTFFocusLost

    private void quantityTFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_quantityTFFocusGained
        // TODO add your handling code here:
        if(quantityTF.getText().equals("Quantity"))
        {
            quantityTF.setText("");
            quantityTF.setForeground(new Color(153,153,153));
        }
        
    }//GEN-LAST:event_quantityTFFocusGained

    private void quantityTFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_quantityTFFocusLost
        // TODO add your handling code here:
        if(quantityTF.getText().equals(""))
        {
            quantityTF.setText("Quantity");
            quantityTF.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_quantityTFFocusLost

    private void supplierTFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_supplierTFFocusGained
        // TODO add your handling code here:    
        if(supplierTF.getText().equals("Status"))
        {
            supplierTF.setText("");
            supplierTF.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_supplierTFFocusGained

    private void supplierTFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_supplierTFFocusLost
        // TODO add your handling code here:
        if(supplierTF.getText().equals(""))
        {
            supplierTF.setText("Status");
            supplierTF.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_supplierTFFocusLost

    private void invPanelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_invPanelBtnActionPerformed
        // TODO add your handling code here:
        if(ordersPanel.isVisible() || servicesPanel.isVisible() || suppliersPanel.isVisible()){
            ordersPanel.setVisible(false);
            servicesPanel.setVisible(false);
            inventPanel.setVisible(true);
            suppliersPanel.setVisible(false);
        }  
    }//GEN-LAST:event_invPanelBtnActionPerformed

    private void ordersSummBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ordersSummBtnActionPerformed
        // TODO add your handling code here:
        if(inventPanel.isVisible() || servicesPanel.isVisible()|| suppliersPanel.isVisible()){
            inventPanel.setVisible(false);
            servicesPanel.setVisible(false);
            ordersPanel.setVisible(true);
            suppliersPanel.setVisible(false);
        }    
    }//GEN-LAST:event_ordersSummBtnActionPerformed

    private void servicesSummBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_servicesSummBtnActionPerformed
        // TODO add your handling code here:
        if(ordersPanel.isVisible() || inventPanel.isVisible()|| suppliersPanel.isVisible()){
            ordersPanel.setVisible(false);
            inventPanel.setVisible(false);
            servicesPanel.setVisible(true);
            suppliersPanel.setVisible(false);
        }
    }//GEN-LAST:event_servicesSummBtnActionPerformed

    private void backBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtn1ActionPerformed
        // TODO add your handling code here:
        dispose();
            MainHub mainhub = new MainHub();
            mainhub.show();
    }//GEN-LAST:event_backBtn1ActionPerformed

    private void ExitBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitBtn1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ExitBtn1ActionPerformed

    private void suppliersSummBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suppliersSummBtn1ActionPerformed
        // TODO add your handling code here:
        if(ordersPanel.isVisible() || inventPanel.isVisible()|| servicesPanel.isVisible()){
            ordersPanel.setVisible(false);
            inventPanel.setVisible(false);
            servicesPanel.setVisible(false);
            suppliersPanel.setVisible(true);
        }
    }//GEN-LAST:event_suppliersSummBtn1ActionPerformed

    private void itemNameTF1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_itemNameTF1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_itemNameTF1FocusGained

    private void itemNameTF1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_itemNameTF1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_itemNameTF1FocusLost

    private void quantityTF1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_quantityTF1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_quantityTF1FocusGained

    private void quantityTF1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_quantityTF1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_quantityTF1FocusLost

    private void backBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtn3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backBtn3ActionPerformed

    private void ExitBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitBtn2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ExitBtn2ActionPerformed

    private void itemNameTF3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_itemNameTF3FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_itemNameTF3FocusGained

    private void itemNameTF3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_itemNameTF3FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_itemNameTF3FocusLost

    private void quantityTF3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_quantityTF3FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_quantityTF3FocusGained

    private void quantityTF3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_quantityTF3FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_quantityTF3FocusLost

    private void supplierTF2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_supplierTF2FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_supplierTF2FocusGained

    private void supplierTF2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_supplierTF2FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_supplierTF2FocusLost

    private void backBtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtn5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backBtn5ActionPerformed

    private void ExitBtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitBtn4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ExitBtn4ActionPerformed

    private void itemNameTF4FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_itemNameTF4FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_itemNameTF4FocusGained

    private void itemNameTF4FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_itemNameTF4FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_itemNameTF4FocusLost

    private void quantityTF4FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_quantityTF4FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_quantityTF4FocusGained

    private void quantityTF4FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_quantityTF4FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_quantityTF4FocusLost

    private void supplierTF3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_supplierTF3FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_supplierTF3FocusGained

    private void supplierTF3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_supplierTF3FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_supplierTF3FocusLost

    private void backBtn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtn6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backBtn6ActionPerformed

    private void ExitBtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitBtn5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ExitBtn5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Database.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Database.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Database.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Database.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Database().setVisible(true);
            }
        });
    }
//hello
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ExitBtn1;
    private javax.swing.JButton ExitBtn2;
    private javax.swing.JButton ExitBtn4;
    private javax.swing.JButton ExitBtn5;
    private javax.swing.JTable allOrdersTable;
    private javax.swing.JButton backBtn1;
    private javax.swing.JButton backBtn3;
    private javax.swing.JButton backBtn5;
    private javax.swing.JButton backBtn6;
    private javax.swing.JButton createBtn;
    private javax.swing.JButton createBtn1;
    private javax.swing.JButton createBtn3;
    private javax.swing.JButton createBtn4;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JButton deleteBtn1;
    private javax.swing.JButton deleteBtn3;
    private javax.swing.JButton deleteBtn4;
    private javax.swing.JButton editBtn;
    private javax.swing.JButton editBtn1;
    private javax.swing.JButton editBtn3;
    private javax.swing.JButton editBtn4;
    private javax.swing.JButton invPanelBtn;
    private javax.swing.JPanel inventPanel;
    private javax.swing.JTextField itemNameTF;
    private javax.swing.JTextField itemNameTF1;
    private javax.swing.JTextField itemNameTF3;
    private javax.swing.JTextField itemNameTF4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel ordersPanel;
    private javax.swing.JButton ordersSummBtn;
    private javax.swing.JTextField quantityTF;
    private javax.swing.JTextField quantityTF1;
    private javax.swing.JTextField quantityTF3;
    private javax.swing.JTextField quantityTF4;
    private javax.swing.JPanel servicesPanel;
    private javax.swing.JButton servicesSummBtn;
    private javax.swing.JComboBox<String> statusCB;
    private javax.swing.JComboBox<String> statusCB2;
    private javax.swing.JComboBox<String> statusCB3;
    private javax.swing.JTextField supplierTF;
    private javax.swing.JTextField supplierTF2;
    private javax.swing.JTextField supplierTF3;
    private javax.swing.JPanel suppliersPanel;
    private javax.swing.JButton suppliersSummBtn1;
    // End of variables declaration//GEN-END:variables
}
